name: Python PEP8 Linter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
#        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        echo "Running critical tests"
        python3 -m flake8 . --isolated --show-source --statistics --extend-ignore=E501,F821,F722 || exit 1
        echo "PASS"

        echo ""
        echo "Running informational tests"
        # exit-zero treats all errors as warnings. Blender defines line length of 120.
        python3 -m flake8 . --isolated --max-complexity=10 --max-line-length=120 --statistics --extend-ignore=F821,F722 && echo "PASS"
        exit 0
#    - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest
